source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Architecture' do

  use_frameworks!

  # Pods for Architecture

  pod 'RealmSwift'
  pod 'RxAlamofire'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
